************* Module data_agent.main
main.py:8:0: E0401: Unable to import 'agent.agent_executor' (import-error)
************* Module data_agent.tools.dataform
tools/dataform.py:13:0: E0401: Unable to import 'utils.tracers' (import-error)
tools/dataform.py:14:0: E0401: Unable to import 'utils.prompt_loader' (import-error)
tools/dataform.py:36:4: R0913: Too many arguments (6/5) (too-many-arguments)
tools/dataform.py:36:4: R0917: Too many positional arguments (6/5) (too-many-positional-arguments)
tools/dataform.py:48:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
tools/dataform.py:68:15: W0718: Catching too general exception Exception (broad-exception-caught)
tools/dataform.py:124:19: W0718: Catching too general exception Exception (broad-exception-caught)
tools/dataform.py:166:23: W0718: Catching too general exception Exception (broad-exception-caught)
tools/dataform.py:219:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
************* Module data_agent.tools.bigquery
tools/bigquery.py:214:0: C0301: Line too long (104/100) (line-too-long)
tools/bigquery.py:223:0: C0301: Line too long (110/100) (line-too-long)
tools/bigquery.py:230:0: C0301: Line too long (101/100) (line-too-long)
tools/bigquery.py:11:0: E0401: Unable to import 'utils.tracers' (import-error)
tools/bigquery.py:244:19: W0718: Catching too general exception Exception (broad-exception-caught)
tools/bigquery.py:209:33: R1721: Unnecessary use of a comprehension, use list(result) instead. (unnecessary-comprehension)
tools/bigquery.py:12:0: C0411: third party import "google.cloud.exceptions.NotFound" should be placed before first party import "utils.tracers.trace_calls"  (wrong-import-order)
tools/bigquery.py:12:0: C0412: Imports from package google are not grouped (ungrouped-imports)
************* Module data_agent.tools.__init__
tools/__init__.py:1:0: C0304: Final newline missing (missing-final-newline)
************* Module data_agent.tools.vertex_ai
tools/vertex_ai.py:1:0: C0114: Missing module docstring (missing-module-docstring)
tools/vertex_ai.py:8:0: E0401: Unable to import 'utils.tracers' (import-error)
tools/vertex_ai.py:9:0: E0401: Unable to import 'utils.prompt_loader' (import-error)
tools/vertex_ai.py:11:0: C0115: Missing class docstring (missing-class-docstring)
tools/vertex_ai.py:31:8: E0401: Unable to import 'tools.bigquery' (import-error)
tools/vertex_ai.py:31:8: C0415: Import outside toplevel (tools.bigquery.BigQueryTools) (import-outside-toplevel)
tools/vertex_ai.py:32:8: W0612: Unused variable 'bigquery_tools' (unused-variable)
tools/vertex_ai.py:54:4: C0116: Missing function or method docstring (missing-function-docstring)
tools/vertex_ai.py:75:19: W0718: Catching too general exception Exception (broad-exception-caught)
tools/vertex_ai.py:66:16: R1705: Unnecessary "elif" after "return", remove the leading "el" from "elif" (no-else-return)
tools/vertex_ai.py:82:24: E1131: unsupported operand type(s) for | (unsupported-binary-operation)
tools/vertex_ai.py:57:8: W0612: Unused variable 'tool_output_model' (unused-variable)
tools/vertex_ai.py:7:0: C0412: Imports from package langchain_core are not grouped (ungrouped-imports)
tools/vertex_ai.py:4:0: W0611: Unused convert_to_openai_function imported from langchain_core.utils.function_calling (unused-import)
************* Module data_agent.utils.config
utils/config.py:74:0: C0304: Final newline missing (missing-final-newline)
utils/config.py:8:0: E0401: Unable to import 'agent.tools_context' (import-error)
utils/config.py:30:4: W0603: Using the global statement (global-statement)
utils/config.py:44:11: W0718: Catching too general exception Exception (broad-exception-caught)
utils/config.py:35:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
utils/config.py:58:4: W0602: Using global for '_CONFIG' but no assignment is done (global-variable-not-assigned)
utils/config.py:9:0: C0411: standard import "os" should be placed before first party import "agent.tools_context.vertexai_tools"  (wrong-import-order)
utils/config.py:10:0: C0411: third party import "yaml" should be placed before first party import "agent.tools_context.vertexai_tools"  (wrong-import-order)
************* Module data_agent.utils.tracers
utils/tracers.py:32:0: C0304: Final newline missing (missing-final-newline)
************* Module data_agent.utils.validations
utils/validations.py:258:0: C0304: Final newline missing (missing-final-newline)
************* Module data_agent.utils.prompt_loader
utils/prompt_loader.py:1:0: C0114: Missing module docstring (missing-module-docstring)
utils/prompt_loader.py:6:0: R0914: Too many local variables (16/15) (too-many-locals)
utils/prompt_loader.py:19:9: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
utils/prompt_loader.py:26:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
utils/prompt_loader.py:35:13: W1514: Using open without explicitly specifying an encoding (unspecified-encoding)
utils/prompt_loader.py:72:4: R1705: Unnecessary "else" after "return", remove the "else" and de-indent the code inside it (no-else-return)
************* Module data_agent.agent.agent_state
agent/agent_state.py:1:0: C0114: Missing module docstring (missing-module-docstring)
************* Module data_agent.agent.tools_context
agent/tools_context.py:10:0: E0401: Unable to import 'tools.dataform' (import-error)
agent/tools_context.py:11:0: E0401: Unable to import 'tools.bigquery' (import-error)
agent/tools_context.py:12:0: E0401: Unable to import 'tools.vertex_ai' (import-error)
agent/tools_context.py:13:0: E0401: Unable to import 'utils.validations' (import-error)
agent/tools_context.py:13:0: W0401: Wildcard import utils.validations (wildcard-import)
agent/tools_context.py:26:23: E0602: Undefined variable 'InformationSchemaInput' (undefined-variable)
agent/tools_context.py:27:24: E0602: Undefined variable 'InformationSchemaOutput' (undefined-variable)
agent/tools_context.py:31:23: E0602: Undefined variable 'FindRelevantDatasetInput' (undefined-variable)
agent/tools_context.py:32:24: E0602: Undefined variable 'FindRelevantDatasetOutput' (undefined-variable)
agent/tools_context.py:36:23: E0602: Undefined variable 'ParseLLMOutputInput' (undefined-variable)
agent/tools_context.py:37:24: E0602: Undefined variable 'ParseLLMOutputOutput' (undefined-variable)
agent/tools_context.py:41:23: E0602: Undefined variable 'UploadAndCompileFilesInput' (undefined-variable)
agent/tools_context.py:42:24: E0602: Undefined variable 'UploadAndCompileFilesOutput' (undefined-variable)
agent/tools_context.py:46:23: E0602: Undefined variable 'FixCompilationErrorsInput' (undefined-variable)
agent/tools_context.py:47:24: E0602: Undefined variable 'FixCompilationErrorsOutput' (undefined-variable)
agent/tools_context.py:51:23: E0602: Undefined variable 'HandleUserRequestInput' (undefined-variable)
agent/tools_context.py:52:24: E0602: Undefined variable 'HandleUserRequestOutput' (undefined-variable)
agent/tools_context.py:56:23: E0602: Undefined variable 'GeneratePipelineCodeInput' (undefined-variable)
agent/tools_context.py:57:24: E0602: Undefined variable 'GeneratePipelineCodeOutput' (undefined-variable)
agent/tools_context.py:61:23: E0602: Undefined variable 'RefineLLMResponseInput' (undefined-variable)
agent/tools_context.py:62:24: E0602: Undefined variable 'RefineLLMResponseOutput' (undefined-variable)
agent/tools_context.py:71:23: E0602: Undefined variable 'ValidateDataInput' (undefined-variable)
agent/tools_context.py:72:24: E0602: Undefined variable 'ValidateDataOutput' (undefined-variable)
************* Module data_agent.agent.agent_executor
agent/agent_executor.py:85:0: C0301: Line too long (101/100) (line-too-long)
agent/agent_executor.py:120:0: C0303: Trailing whitespace (trailing-whitespace)
agent/agent_executor.py:16:0: E0401: Unable to import 'agent.agent_state' (import-error)
agent/agent_executor.py:17:0: E0401: Unable to import 'tools.dataform' (import-error)
agent/agent_executor.py:18:0: E0401: Unable to import 'tools.bigquery' (import-error)
agent/agent_executor.py:19:0: E0401: Unable to import 'tools.vertex_ai' (import-error)
agent/agent_executor.py:20:0: E0401: Unable to import 'utils.tracers' (import-error)
agent/agent_executor.py:21:0: E0401: Unable to import 'utils.validations' (import-error)
agent/agent_executor.py:21:0: W0401: Wildcard import utils.validations (wildcard-import)
agent/agent_executor.py:23:0: E0401: Unable to import 'agent.tasks.get_initial_user_request' (import-error)
agent/agent_executor.py:24:0: E0401: Unable to import 'agent.tasks.elicit_schema' (import-error)
agent/agent_executor.py:25:0: E0401: Unable to import 'agent.tasks.generate_code' (import-error)
agent/agent_executor.py:26:0: E0401: Unable to import 'agent.tasks.identify_dataform_files' (import-error)
agent/agent_executor.py:27:0: E0401: Unable to import 'agent.tasks.upload_files' (import-error)
agent/agent_executor.py:28:0: E0401: Unable to import 'agent.tasks.ask_clarifications' (import-error)
agent/agent_executor.py:29:0: E0401: Unable to import 'agent.tasks.ask_for_further_input' (import-error)
agent/agent_executor.py:30:0: E0401: Unable to import 'agent.tasks.decide_to_continue' (import-error)
agent/agent_executor.py:112:4: R1702: Too many nested blocks (11/5) (too-many-nested-blocks)
agent/agent_executor.py:186:16: R1723: Unnecessary "else" after "break", remove the "else" and de-indent the code inside it (no-else-break)
agent/agent_executor.py:105:0: R0912: Too many branches (21/12) (too-many-branches)
agent/agent_executor.py:183:20: W0612: Unused variable 'user_request_dummy' (unused-variable)
agent/agent_executor.py:23:0: C0412: Imports from package agent are not grouped (ungrouped-imports)

------------------------------------------------------------------
Your code has been rated at 4.67/10 (previous run: 4.56/10, +0.11)

